# Computer Vision :-

> Open cv is a libary in py. which use for working on image.

> opencv use (B,G,R) Format.

# Image :-

> It is a collection of pixels.

> pixel is really a matrix which have 3 value (B,G,R). The  value range from (0-255)


In [43]:
pip install opencv-python


Note: you may need to restart the kernel to use updated packages.


In [44]:
import cv2

In [45]:
img=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg")
cv2.imshow("Suraj",img)
cv2.waitKey(10000 ) # in ms 1000ms == 1sec
cv2.destroyWindow("Suraj")

In [46]:
img=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg")

In [47]:
# mixing the image pixel
f_m=img.flatten()

In [48]:
import numpy as np
np.random.shuffle(f_m)
f_m=f_m.reshape(735,742,3)


In [49]:
cv2.imshow("Suraj",f_m)
cv2.waitKey(10000 ) # in ms 1000ms == 1sec
cv2.destroyWindow("Suraj") # so we can arrange pixel in sequance so we can create any type image.

# Broadcasting in image :-

>  Image is a base is array and array is support broadcasting


In [50]:
import numpy as np 
b=np.arange(1,5)
b*10

array([10, 20, 30, 40])

In [51]:
image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg") 
a=image-5
cv2.imshow("Original",image)
cv2.imshow("New",a)
cv2.waitKey()
cv2.destroyAllWindows()

In [52]:
# color image to black and white 
# option 1 :- 
image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg",0)
cv2.imshow("hello",image)
cv2.waitKey()
cv2.destroyWindow("hello")

In [53]:
# option 2:-
image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg")
a=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow("hello",a)
cv2.waitKey()
cv2.destroyWindow("hello")

In [54]:
# option 3:- by color spliting .
image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg")
b,g,r=cv2.split(image)
cv2.imshow("blue",b)
cv2.imshow("Green",g)
cv2.imshow("Red",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [55]:
b

array([[124, 124, 124, ..., 192, 196, 200],
       [124, 124, 124, ..., 194, 198, 202],
       [124, 124, 124, ..., 197, 200, 205],
       ...,
       [250, 248, 250, ..., 251, 250, 251],
       [249, 248, 248, ..., 252, 250, 252],
       [251, 251, 251, ..., 253, 253, 253]], dtype=uint8)

In [56]:
g

array([[117, 117, 117, ..., 195, 199, 203],
       [117, 117, 117, ..., 197, 201, 205],
       [117, 117, 117, ..., 200, 203, 208],
       ...,
       [251, 251, 252, ..., 255, 255, 255],
       [252, 252, 251, ..., 254, 254, 254],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [57]:
r

array([[108, 108, 108, ..., 203, 207, 211],
       [108, 108, 108, ..., 205, 209, 213],
       [108, 108, 108, ..., 205, 208, 213],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [58]:
image

array([[[124, 117, 108],
        [124, 117, 108],
        [124, 117, 108],
        ...,
        [192, 195, 203],
        [196, 199, 207],
        [200, 203, 211]],

       [[124, 117, 108],
        [124, 117, 108],
        [124, 117, 108],
        ...,
        [194, 197, 205],
        [198, 201, 209],
        [202, 205, 213]],

       [[124, 117, 108],
        [124, 117, 108],
        [124, 117, 108],
        ...,
        [197, 200, 205],
        [200, 203, 208],
        [205, 208, 213]],

       ...,

       [[250, 251, 255],
        [248, 251, 255],
        [250, 252, 255],
        ...,
        [251, 255, 255],
        [250, 255, 255],
        [251, 255, 255]],

       [[249, 252, 255],
        [248, 252, 255],
        [248, 251, 255],
        ...,
        [252, 254, 255],
        [250, 254, 255],
        [252, 254, 255]],

       [[251, 255, 255],
        [251, 255, 255],
        [251, 255, 255],
        ...,
        [253, 255, 255],
        [253, 255, 255],
        [253, 255, 255]]

In [59]:
# merge the all color :-
rt=cv2.merge([b,g,r])
cv2.imshow("Red",rt)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:

image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\me.jpg")
b,g,r=cv2.split(image)
cv2.imshow("blue",b)
cv2.imshow("Green",g)
cv2.imshow("Red",r)
cv2.waitKey()
cv2.destroyAllWindows()

In [61]:
# Play with image.
img7=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\demo.jpg")
img2=cv2.convertScaleAbs(img,alpha=2,beta=45)   #alpha works on edgeor sharpness
cv2.imshow("Scale",img2) 
cv2.imshow("Orignal",img7)                        #beta work on brigtness.
cv2.waitKey(10000 ) 
cv2.destroyAllWindows()

In [62]:
# marge  2 photos
image=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\me.jpg")
img3=cv2.resize(image,(735,742))
cv2.imwrite(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\me_resize.jpg",img3)
img=cv2.imread(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\Image\me_resize.jpg")
cv2.imshow("orginal",image) 
cv2.imshow("Resize",img)                        #beta work on brigtness.
cv2.waitKey() 
cv2.destroyAllWindows()

In [69]:
a=cv2.addWeighted(img,0.5,img7,0.3,10) 
cv2.imshow("Merge",a)                    
cv2.waitKey() 
cv2.destroyAllWindows()