# Scalling:- 
## aranging the data on a scale is called scalling.
## In Python , sklearn having scalling but minmax scalling and standard  scalling are used more in the industry.

In [134]:
import pandas as pb
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\csvdata.csv")
df

Unnamed: 0       City     Price  Area                         Location  \
0               0  Bangalore  30000000  3340                 JP Nagar Phase 1   
1               1  Bangalore   7888000  1045       Dasarahalli on Tumkur Road   
2               2  Bangalore   4866000  1179  Kannur on Thanisandra Main Road   
3               3  Bangalore   8358000  1675                     Doddanekundi   
4               4  Bangalore   6845000  1670                          Kengeri   
...           ...        ...       ...   ...                              ...   
29130        7714     Mumbai  14500000  1180                   Mira Road East   
29131        7715     Mumbai  14500000   530                     Naigaon East   
29132        7716     Mumbai   4100000   700                         Shirgaon   
29133        7717     Mumbai   2750000   995                   Mira Road East   
29134        7718     Mumbai   2750000  1020                   Mira Road East   

       No. of Bedrooms  
0                    4  
1                    2  
2                    2  
3                    3  
4                    3  
...                ...  
29130                2  
29131                1  
29132                1  
29133                2  
29134                2  

[29135 rows x 6 columns]

In [135]:
df2=df.iloc[:,[1,2,3,5]]

df2

City     Price  Area  No. of Bedrooms
0      Bangalore  30000000  3340                4
1      Bangalore   7888000  1045                2
2      Bangalore   4866000  1179                2
3      Bangalore   8358000  1675                3
4      Bangalore   6845000  1670                3
...          ...       ...   ...              ...
29130     Mumbai  14500000  1180                2
29131     Mumbai  14500000   530                1
29132     Mumbai   4100000   700                1
29133     Mumbai   2750000   995                2
29134     Mumbai   2750000  1020                2

[29135 rows x 4 columns]

In [136]:
df2.City.value_counts()

City
Mumbai       6925
Kolkata      6275
Bangalore    5521
Chennai      4307
Delhi        4109
Hyderabad    1998
Name: count, dtype: int64

# City is not better for model  because it have many city the algo. must be confused.To resolve it we use one-one encoding

In [137]:
df2.City=df2.City.map({"Mumbai":0,"Kolkata":1,"Bangalore":2,"Chennai":3,"Delhi":4,"Hyderabad":5})
df2

C:\Users\Paramjeet\AppData\Local\Temp\ipykernel_15996\1657542469.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.City=df2.City.map({"Mumbai":0,"Kolkata":1,"Bangalore":2,"Chennai":3,"Delhi":4,"Hyderabad":5})


City     Price  Area  No. of Bedrooms
0         2  30000000  3340                4
1         2   7888000  1045                2
2         2   4866000  1179                2
3         2   8358000  1675                3
4         2   6845000  1670                3
...     ...       ...   ...              ...
29130     0  14500000  1180                2
29131     0  14500000   530                1
29132     0   4100000   700                1
29133     0   2750000   995                2
29134     0   2750000  1020                2

[29135 rows x 4 columns]

In [138]:
df2=df2.iloc[:,[0,2,3,1]]
df2

City  Area  No. of Bedrooms     Price
0         2  3340                4  30000000
1         2  1045                2   7888000
2         2  1179                2   4866000
3         2  1675                3   8358000
4         2  1670                3   6845000
...     ...   ...              ...       ...
29130     0  1180                2  14500000
29131     0   530                1  14500000
29132     0   700                1   4100000
29133     0   995                2   2750000
29134     0  1020                2   2750000

[29135 rows x 4 columns]

In [139]:
# feature:-
x=df2.drop("Price",axis=1)
x=x.values              
x.ndim                    

2

In [140]:
# Target:-
y=df2.Price
y=y.values
y.ndim

1

In [141]:
from sklearn.model_selection import train_test_split 
x_train,x_test,Y_train,Y_test=train_test_split(x,y,train_size=0.7,random_state=52)

In [142]:
print('x_train :-',x_train,end="\n")
print('x_test :-',x_test,end="\n")
print('Y_train :-',Y_train,end="\n")
print('Y_test :-',Y_test,end="\n")

x_train :- [[   2 1892    3]
 [   0  660    1]
 [   2  903    2]
 ...
 [   4  750    3]
 [   4 1200    2]
 [   0  500    1]]
x_test :- [[   3 1734    3]
 [   2 1830    3]
 [   2 1260    2]
 ...
 [   0 1040    2]
 [   0  676    2]
 [   1 1113    3]]
Y_train :- [ 5200000  6000000  5300000 ...  3651000 15000000  3800000]
Y_test :- [10900000 11500000  6600000 ...  5800000 10700000  4639000]


In [143]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model

LinearRegression()

In [144]:
model.fit(x_train,Y_train)

LinearRegression()

In [145]:
#On testing data :-
x_test_predict=model.predict(x_test)
x_test_predict

array([14650482.44412488, 16208060.30576868, 12581330.46336003, ...,
       11230983.56641387,  7285733.67863454,  8953857.51146578])

In [146]:
from sklearn.metrics import r2_score
#Note:- r2_score is use for regression and accuracy_score use in classification.
r2_score(Y_test,x_test_predict)*100

5.928800612390495

In [147]:
#on train data :-
x_train_predict=model.predict(x_train)
x_train_predict

array([16880053.4185223 ,  9663587.45663729,  8711950.7657303 , ...,
        3468229.03207437, 10896869.75432209,  7929411.68178923])

In [148]:
r2_score(Y_train,x_train_predict)*100

8.342521086352894

# As we see in above score we don't get much accuracy in this predict which is not better for production level.To handle this we use scalling.

In [149]:
m1,m2,m3=model.coef_


print("M1 :-",m1)
print("M2 :-",m2)
print("M3 :-",m3)

M1 :- -517072.3967349615
M2 :- 10838.598592800365
M3 :- -2551271.3554875557


In [150]:
c=model.intercept_
c

5061383.740876607

In [151]:
x1,x2,x3=[2,3340,4]
print("X1 :-",x1)
print("X2 :-",x2)
print("X3 :-",x3)

X1 :- 2
X2 :- 3340
X3 :- 4


# Line/slop :-
 ##       y=mx+c for 1d , but in above dataset we have 3 parmeter then y=m1x1+m2x2+m3x3+c

In [152]:
print("M1*X1")
m1*x1

M1*X1


-1034144.793469923

In [153]:
print("M2*X2")
m2*x2

M2*X2


36200919.299953215

In [154]:
print("M3*X3")
m3*x3

M3*X3


-10205085.421950223

## As we seen above  3 lines m3 is more that influnce the equation of line.
## There 2 way too handle it :-
## 1) Delete that column which is not a better option but sometime okay.
## 2) Using scaling.

In [155]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
sc

MinMaxScaler()

In [156]:
x_scale=sc.fit_transform(x)
x_scale ## First time when we scale the data then we use fit_transform and other time we use transform.

array([[0.4       , 0.19873418, 0.375     ],
       [0.4       , 0.05348101, 0.125     ],
       [0.4       , 0.06196203, 0.125     ],
       ...,
       [0.        , 0.03164557, 0.        ],
       [0.        , 0.05031646, 0.125     ],
       [0.        , 0.05189873, 0.125     ]])

In [157]:
x_scale_train,x_scale_test,Y_train,Y_test=train_test_split(x_scale,y,train_size=0.7,random_state=52)

In [158]:
print('x_scale_train :-',x_scale_train,end="\n")
print('x_scale_test :-',x_scale_test,end="\n")
print('Y_train :-',Y_train,end="\n")
print('Y_test :-',Y_test,end="\n")

x_scale_train :- [[0.4        0.10708861 0.25      ]
 [0.         0.02911392 0.        ]
 [0.4        0.04449367 0.125     ]
 ...
 [0.8        0.03481013 0.25      ]
 [0.8        0.06329114 0.125     ]
 [0.         0.01898734 0.        ]]
x_scale_test :- [[0.6        0.09708861 0.25      ]
 [0.4        0.10316456 0.25      ]
 [0.4        0.06708861 0.125     ]
 ...
 [0.         0.05316456 0.125     ]
 [0.         0.03012658 0.125     ]
 [0.2        0.05778481 0.25      ]]
Y_train :- [ 5200000  6000000  5300000 ...  3651000 15000000  3800000]
Y_test :- [10900000 11500000  6600000 ...  5800000 10700000  4639000]


In [159]:
model.fit(x_scale_train,Y_train)

LinearRegression()

In [160]:
#On testing data :-
x_scale_test_predict=model.predict(x_scale_test)
x_scale_test_predict

array([14650482.44412494, 16208060.30576873, 12581330.46336007, ...,
       11230983.5664139 ,  7285733.67863457,  8953857.51146582])

In [161]:
r2_score(Y_test,x_scale_test_predict)*100

5.928800612390495

In [162]:
#on train data :-
x_scale_train_predict=model.predict(x_scale_train)
x_scale_train_predict

array([16880053.41852235,  9663587.45663732,  8711950.76573034, ...,
        3468229.03207441, 10896869.75432213,  7929411.68178925])

In [163]:
r2_score(Y_train,x_scale_train_predict)*100

8.34252108635286

# Theoritical explanation of scalar :-

## MinMaxScaler :-
###             It is most comman used scalar in sk-learn. This work on min-max values .

# Foramula :-  (org_value-min_value)/max_value-min_value

# Example :-

In [164]:
# according to sk-leran :-
import numpy as np
a=[[5],[2],[9],[6]]
b=np.array(a)
b

array([[5],
       [2],
       [9],
       [6]])

In [165]:
sc.fit_transform(b)

array([[0.42857143],
       [0.        ],
       [1.        ],
       [0.57142857]])

In [166]:
# according to formula :-
min=b.min()
max=b.max()
d=max-min
(b-min)/d

array([[0.42857143],
       [0.        ],
       [1.        ],
       [0.57142857]])

In [167]:
# Making a my func. for min-max :-
def sasta_min_max_scalar(arg):
    min=arg.min()
    max=arg.max()
    d=max-min
    return((arg-min)/d)

In [168]:
a=[[5],[25],[9],[6],[95],[56],[49],[60]]
e=np.array(a)
e

array([[ 5],
       [25],
       [ 9],
       [ 6],
       [95],
       [56],
       [49],
       [60]])

In [169]:
sasta_min_max_scalar(e)

array([[0.        ],
       [0.22222222],
       [0.04444444],
       [0.01111111],
       [1.        ],
       [0.56666667],
       [0.48888889],
       [0.61111111]])

In [170]:
# class making :-
class min_max_scalar():
    def sasta_min_max_scalar01(self,arg):
        min=arg.min()
        max=arg.max()
        d=max-min
        return((arg-min)/d)

In [171]:
s=min_max_scalar()

In [172]:
s.sasta_min_max_scalar01(e)


array([[0.        ],
       [0.22222222],
       [0.04444444],
       [0.01111111],
       [1.        ],
       [0.56666667],
       [0.48888889],
       [0.61111111]])

# Standardscalar :- It is also use more . it use on distributed to make it in bell shape diagram.it use standard davieastion = (variance)**2