# Activation fuction :- These are use too  make more accurate the prediction . There are 2 type type of function use in classification regression.

## 1.) Sigmoid function (ovr):- it is best for only 2 class.

## 2.) Softmax function (multimonial):- it is best for more than 2 class.

In [50]:
import numpy as np
import pandas as pb
import matplotlib.pyplot as plt
import seaborn as sn

In [51]:
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [52]:
df.species.value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [53]:
feature=df.iloc[:,:4].values
print("dimension :- ",feature.ndim,"\n",feature) #2d array

dimension :-  2 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5

In [54]:
target=df.species

In [55]:
from sklearn.linear_model import LogisticRegression

## ---> Model by Auto (Work only some time) :-

In [56]:
model1=LogisticRegression()
model1

LogisticRegression()

In [57]:
model1.fit(feature,target)

LogisticRegression()

In [58]:
model1.predict([[4.9,  3. , 1.4, 0.2]])

array(['Iris-setosa'], dtype=object)

In [59]:
model1.predict_proba([[4.9,  3. , 1.4, 0.2]])

array([[9.71720996e-01, 2.82789740e-02, 2.98017352e-08]])

## ---> Model by ovr (sgmoid) :-

In [60]:
model=LogisticRegression(multi_class='ovr')
model

LogisticRegression(multi_class='ovr')

In [61]:
model.fit(feature,target)

LogisticRegression(multi_class='ovr')

In [62]:
model.predict([[4.9,  3. , 1.4, 0.2]])

array(['Iris-setosa'], dtype=object)

In [63]:
model.predict_proba([[4.9,  3. , 1.4, 0.2]])

array([[7.82524451e-01, 2.17474228e-01, 1.32093735e-06]])

## ---> Model by multinomial (softmax) :-

In [64]:
model2=LogisticRegression(multi_class='multinomial')
model2

LogisticRegression(multi_class='multinomial')

In [65]:
model2.fit(feature,target)

LogisticRegression(multi_class='multinomial')

In [66]:
model2.predict([[4.9,  3. , 1.4, 0.2]])

array(['Iris-setosa'], dtype=object)

In [67]:
model2.predict_proba([[4.9,  3. , 1.4, 0.2]])

array([[9.71720996e-01, 2.82789740e-02, 2.98017352e-08]])