# Ensemble Learning :-
## -->  Ensemble Learning is divide into 3 parts :-

# 1.) Bagging  2.) Adaboost (Boosting)   3.) votting

# -> Comman Point in All parts :-


> 1.) They use small-small (n no. of modal) modal internally.(Like :- decision Tree,linear regression etc.)

> 2.) Some modal use bootstrap datasets.(To suffle the datasets differently for n modal.)

# 1.) Bagging :-


# 1.) Random Forest :-


> a.) Random forest use 100 decision tree (estimator) internally.

> b.) we can't able to change the no. of modal in random forestc Or type of modal.

In [52]:
import pandas as pb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

In [53]:
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [54]:
feature=df.iloc[:,0:4].values
feature

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [55]:
target=df.species
target

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

# Data scalling (Feature) :- 

In [56]:
from sklearn.preprocessing import MinMaxScaler

In [57]:
sc=MinMaxScaler()

In [58]:
feature_sc=sc.fit_transform(feature)

# Train and Test Spliting :- 

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
feature_train,target_tarin,feature_Test,target_Test=train_test_split(feature_sc,target,train_size=0.7,random_state=32)

# Modal :-

In [61]:
modal=RandomForestClassifier()
modal

RandomForestClassifier()

In [62]:
modal.fit(feature_train,feature_Test)

RandomForestClassifier()

In [63]:
target_pred=modal.predict(target_tarin)
feature_pred=modal.predict(feature_train)

# Check the accuracy of modal :-

In [64]:
from sklearn.metrics import accuracy_score

In [65]:
t_sc=accuracy_score(target_pred,target_Test)
t_sc

1.0

In [66]:
f_sc=accuracy_score(feature_pred,feature_Test)
f_sc

1.0

# -> So this modal is fizible in real life market. Because bias and variance is less than 5 %.

In [67]:
def suraj():

        import pandas as pb
        import numpy as np
        import matplotlib.pyplot as plt
        from sklearn.ensemble import RandomForestClassifier
        df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
        feature=df.iloc[:,0:4].values
        print("Feature Dimension :- ",feature.ndim,"\n")
        target=df.species
        print("Target Dimension :- ",target.ndim,"\n")
        from sklearn.preprocessing import MinMaxScaler
        sc=MinMaxScaler()
        feature_sc=sc.fit_transform(feature)
        from sklearn.model_selection import train_test_split
        feature_train,target_tarin,feature_Test,target_Test=train_test_split(feature_sc,target,train_size=0.7,random_state=32)
        modal=RandomForestClassifier()
        print("Modal is :- ",modal,"\n")
        modal.fit(feature_train,feature_Test)
        target_pred=modal.predict(target_tarin)
        feature_pred=modal.predict(feature_train)
        from sklearn.metrics import accuracy_score
        t_sc=accuracy_score(target_pred,target_Test)
        print("Testing Score:-",t_sc,"\n")
        f_sc=accuracy_score(feature_pred,feature_Test)
        print("Training Score :-",f_sc,"\n")


In [68]:
suraj()

Feature Dimension :-  2 

Target Dimension :-  1 

Modal is :-  RandomForestClassifier() 

Testing Score:- 0.9555555555555556 

Training Score :- 1.0 



# RandomForest classifier is Not good due to dicisontree.

# ______________________________________________________________________________________________________________________________________________________________________________________

# -> Bagging :-

> By default it use 10 estimator and we adjust the no. of estimator.

> By default it use Decision Tree and we adjust the modal.

> High no. of estimator use large memory.

> High no. of estimator give good result.

> It also have beggingregressor but it work good with modal like :- linear etc.

> It use only single type of small modal at a time.

# ______________________________________________________________________________________________________________________________________________________________________________________


In [69]:
import pandas as pb
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import BaggingClassifier

In [70]:
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [71]:
feature=df.iloc[:,0:4].values
feature

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [72]:
target=df.species
target

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [73]:
from sklearn.preprocessing import MinMaxScaler

In [74]:
sc=MinMaxScaler()
feature_sc=sc.fit_transform(feature)
from sklearn.model_selection import train_test_split
x_train,x_test,y_Train,y_Test=train_test_split(feature_sc,target,train_size=0.7,random_state=32)
from sklearn.linear_model import LogisticRegression
s_m_l=LogisticRegression(max_iter=1000,multi_class='multinomial')

In [75]:
modal=BaggingClassifier(estimator=s_m_l,n_estimators=1500)
modal

BaggingClassifier(estimator=LogisticRegression(max_iter=1000,
                                               multi_class='multinomial'),
                  n_estimators=1500)

In [76]:
modal.fit(x_train,y_Train)

BaggingClassifier(estimator=LogisticRegression(max_iter=1000,
                                               multi_class='multinomial'),
                  n_estimators=1500)

In [77]:
tar_pred=modal.predict(x_train)
test_pred=modal.predict(x_test)

In [78]:
from sklearn.metrics import accuracy_score
test_sc=accuracy_score(test_pred,y_Test)
print("Testing Score:-",test_sc,"\n")
train_sc=accuracy_score(tar_pred,y_Train)
print("Training Score :-",train_sc,"\n")

Testing Score:- 0.9333333333333333 

Training Score :- 0.9428571428571428 



# Adaboost (Boosting) :-

> This modal not use bootstrap technique.

> In this modal we inherit enseble or other modal as a Base Modal.

> This modal work on Weight and which close to deep learning.

> By default No. of base modal is 50.

> This modal work good on classification but not in regression.

> scalling is must for this modal.

In [79]:
import pandas as pb
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [80]:
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [81]:
featur=df.iloc[:,0:4].values
featur

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [82]:
Target=df.species.values
target

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

# Scalling :-

In [83]:
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
s_fc=scale.fit_transform(featur)

# Splitting :-

In [84]:
from sklearn.model_selection import train_test_split
x_train,y_Train,x_test,y_Test=train_test_split(s_fc,target,train_size=0.7,random_state=42,shuffle=True)
y_Train

array([[0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.36111111, 0.20833333,

# Model :-

In [85]:
from sklearn.ensemble import RandomForestClassifier
base_M=RandomForestClassifier(max_depth=3)
from sklearn.ensemble import AdaBoostClassifier
modal=AdaBoostClassifier(estimator=base_M,n_estimators=150)

In [86]:
modal.fit(x_train,x_test)

c:\Users\Paramjeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(estimator=RandomForestClassifier(max_depth=3),
                   n_estimators=150)

In [87]:
smaple=scale.transform([[0.5       , 0.33333333, 0.62711864, 0.45833333]])

In [88]:
modal.predict(smaple)

array(['Iris-setosa'], dtype=object)

In [89]:
modal.predict_proba(smaple)

array([[9.26180652e-01, 7.37887544e-02, 3.05937749e-05]])

# Votting :-

> That use diff. type of modals (estimator) at a same time.

> This work on the concept of votting . The assign diff. value of vote to modals internally by which good output is gernated. 

# For ex :-

# modal         value of    Total       vote
                   vote        vote        count

#  phd     -->    1     -->   50   -->   50
#  
#  Btech   -->    0.5   -->   50   -->   25
#  
#  10th    -->    0.1   -->   50   -->    5

> not use the bootstrap method.

In [90]:
import pandas as pb
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
df=pb.read_csv(r"A:\Ducat\PYTHON\phyton\data analytics\MACHINE LEARNING\DATASETS\IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [91]:
x=df.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [92]:
y=df.species.values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [141]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x_sc=sc.fit_transform(x)
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(x_sc,y,train_size=0.7,random_state=20)

In [142]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
m1=LogisticRegression(max_iter=2000)
m2=DecisionTreeClassifier(max_depth=3)
m3=RandomForestClassifier(max_depth=2)
modal=VotingClassifier(estimators=[("1st modal",m1),("2nd modal",m2),("3rd modal",m3)])

In [143]:
modal.fit(x_train1,y_train1)

VotingClassifier(estimators=[('1st modal', LogisticRegression(max_iter=2000)),
                             ('2nd modal', DecisionTreeClassifier(max_depth=3)),
                             ('3rd modal',
                              RandomForestClassifier(max_depth=2))])

In [144]:
xtest_p=modal.predict(x_test1)
xtrain_p=modal.predict(x_train1)

In [145]:
from sklearn.metrics import accuracy_score

In [146]:
print("Training score :- ",accuracy_score(y_train1,xtrain_p))
print("Testing score :- ",accuracy_score(y_test1,xtest_p))

Training score :-  0.9809523809523809
Testing score :-  0.8888888888888888
