# polynomial feature :-

> When we in lack of feature then we use it.

> internally it use algebra.

> by default it create 2 feature.It is ram expensive process.so more feature is not good for production.

> for ex:-

 
 >       Feature                        feature  (x^0)      (x^1)         (x^2)       (x^3)    
 
 >       1                                         1           1            1            1
 
 >       2                                         1           2            4            8       
 
 >       3            ---->                        1           3            9            27  
 
 >       4                                         1           4            16           64
 
 >       5                                         1           5            25           125

In [39]:
import numpy as np
import pandas as pb


In [40]:
df=pb.read_csv(r"C:\Users\Paramjeet\Desktop\MACHINE LEARNING\archive (4)\Salary Data.csv")
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [41]:
df=df.dropna()

In [42]:
feature=df[["Years of Experience"]].values
feature

array([[ 5. ],
       [ 3. ],
       [15. ],
       [ 7. ],
       [20. ],
       [ 2. ],
       [12. ],
       [ 4. ],
       [ 1. ],
       [10. ],
       [ 3. ],
       [18. ],
       [ 6. ],
       [14. ],
       [ 2. ],
       [16. ],
       [ 7. ],
       [12. ],
       [ 0. ],
       [22. ],
       [ 5. ],
       [19. ],
       [ 2. ],
       [ 9. ],
       [13. ],
       [ 3. ],
       [11. ],
       [ 1. ],
       [15. ],
       [ 6. ],
       [25. ],
       [ 4. ],
       [ 3. ],
       [10. ],
       [20. ],
       [ 2. ],
       [ 7. ],
       [14. ],
       [ 1. ],
       [21. ],
       [ 5. ],
       [18. ],
       [ 3. ],
       [ 8. ],
       [13. ],
       [ 2. ],
       [ 5. ],
       [16. ],
       [11. ],
       [ 0. ],
       [22. ],
       [ 7. ],
       [12. ],
       [19. ],
       [ 3. ],
       [ 9. ],
       [ 2. ],
       [17. ],
       [ 4. ],
       [ 7. ],
       [23. ],
       [ 3. ],
       [12. ],
       [21. ],
       [ 1. ],
       [10. ],
       [19

In [43]:
target=df.Salary

In [44]:
from sklearn.preprocessing import PolynomialFeatures
pf=PolynomialFeatures(degree=3)
pf

PolynomialFeatures(degree=3)

In [45]:
pff=pf.fit_transform(feature)
pff

array([[1.000e+00, 5.000e+00, 2.500e+01, 1.250e+02],
       [1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01],
       [1.000e+00, 1.500e+01, 2.250e+02, 3.375e+03],
       ...,
       [1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00],
       [1.000e+00, 7.000e+00, 4.900e+01, 3.430e+02],
       [1.000e+00, 1.500e+01, 2.250e+02, 3.375e+03]])

In [46]:
from sklearn.linear_model import LinearRegression
modal=LinearRegression()
modal

LinearRegression()

In [47]:
modal.fit(pff,target)

LinearRegression()

In [48]:
sample=pf.transform([[ 5. ]])

modal.predict(sample)

array([66828.06672277])